language: objective-c
before_install:
  - gem install cocoapods
osx_image: xcode9
before_script: cd MixpanelDemo
podfile: MixpanelDemo/Podfile
branches:
  only:
  - master
env:
  global:
  - WORKSPACE=MixpanelDemo.xcworkspace
  - SCHEME=MixpanelDemo
  - IOS_SDK=iphonesimulator11.0
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 5"          SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
#    - DESTINATION="platform=iOS Simulator,OS=8.2,name=iPhone 5"           SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
#    - DESTINATION="platform=iOS Simulator,OS=8.3,name=iPhone 5S"          SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
#    - DESTINATION="platform=iOS Simulator,OS=8.4,name=iPhone 6"           SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
#    - DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"           SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
#    - DESTINATION="platform=iOS Simulator,OS=9.1,name=iPhone 6 Plus"      SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
#    - DESTINATION="platform=iOS Simulator,OS=9.2,name=iPhone 6S"          SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,OS=9.1,name=iPhone 6s Plus"     SCHEME="$SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      cd .. && pod lib lint --allow-warnings && cd MixpanelDemo;
    fi
