language: objective-c
before_install:
  - gem install cocoapods -v 1.3.1
osx_image: xcode9.3
before_script: cd MixpanelDemo
podfile: MixpanelDemo/Podfile
branches:
  only:
  - master
env:
  global:
  - WORKSPACE=MixpanelDemo.xcworkspace
  - SCHEME=MixpanelDemo
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"    SCHEME="$SCHEME"    RUN_TESTS="YES"     POD_LINT="YES"
    - DESTINATION="OS=11.1,name=iPhone X"   SCHEME="$SCHEME"    RUN_TESTS="YES"     POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      cd .. && pod _1.3.1_ lib lint --allow-warnings && cd MixpanelDemo;
    fi
